---
# ==============================================================================
# PostgreSQL PGDG Repository Configuration
# ==============================================================================

- name: "PostgreSQL | repository | Configure PGDG deb822 apt repository"
  ansible.builtin.deb822_repository:
    name: "pgdg"
    types:
      - "deb"
    uris:
      - "{{ __postgresql_pgdg_repo_uri }}"
    suites:
      - "{{ ansible_facts['distribution_release'] }}-pgdg"
    components:
      - "main"
    signed_by: "{{ __postgresql_pgdg_key_url }}"
    state: present
  become: true
  notify: "update apt cache"

- name: "PostgreSQL | repository | Flush handlers to update apt cache immediately if repository changed"
  ansible.builtin.meta: flush_handlers
